# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFilterDtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_name', models.CharField(max_length=250)),
                ('filter_tooltip', models.CharField(blank=True, max_length=250)),
                ('lang_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFilterMst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_order', models.IntegerField(default=0)),
                ('active_flag', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=250)),
                ('image_path', models.ImageField(upload_to=b'')),
                ('filter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.ImageFilterDtl')),
            ],
        ),
        migrations.AddField(
            model_name='imagefilterdtl',
            name='filter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.ImageFilterMst'),
        ),
    ]
