# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefiltermst',
            name='active_flag',
            field=models.IntegerField(default=1),
        ),
    ]
