# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170422_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefiltermst',
            name='filter_tag',
            field=models.CharField(default='', max_length=250),
        ),
    ]
