# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavMenuDtls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navMenuName', models.CharField(max_length=250)),
                ('navMenuTooltip', models.CharField(max_length=250)),
                ('langId', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NavMenuMst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentNavMenu', models.IntegerField(default=-1)),
                ('navOrder', models.IntegerField(default=0)),
                ('activeFlag', models.IntegerField(default=0)),
            ],
        ),
    ]
