# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navmenudtls',
            name='navMenuId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='homepage.NavMenuMst'),
            preserve_default=False,
        ),
    ]
