# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_navmenudtls_navmenuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navmenumst',
            name='activeFlag',
            field=models.IntegerField(default=-1),
        ),
    ]
