# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20170416_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelDtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_header', models.CharField(max_length=250)),
                ('panel_body', models.TextField()),
                ('panel_footer', models.CharField(max_length=250)),
                ('langId', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PanelMst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_key', models.CharField(max_length=250)),
                ('panel_order', models.IntegerField(default=0)),
                ('activeFlag', models.IntegerField(default=1)),
                ('panel_width', models.IntegerField(default=4)),
                ('panel_offset', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='navmenumst',
            name='activeFlag',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paneldtl',
            name='panel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.PanelMst'),
        ),
    ]
