# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20170417_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paneldtl',
            name='panel_footer',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
