# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 11:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20170417_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='navmenumst',
            name='urlPageName',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='paneldtl',
            name='panel_body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
