# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 00:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20170422_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentEventsCardDtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image_path', models.ImageField(null=True, upload_to=b'')),
                ('image_name', models.CharField(max_length=250)),
                ('profile_image_path', models.ImageField(null=True, upload_to=b'')),
                ('profile_image_name', models.CharField(max_length=250)),
                ('event_title', models.CharField(max_length=250)),
                ('event_body', ckeditor.fields.RichTextField()),
                ('event_body_back', ckeditor.fields.RichTextField()),
                ('event_footer', models.CharField(blank=True, max_length=250)),
                ('langId', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RecentEventsCardMst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=250)),
                ('card_order', models.IntegerField(default=0)),
                ('activeFlag', models.IntegerField(default=1)),
                ('card_width', models.IntegerField(default=3)),
                ('card_offset', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='recenteventscarddtl',
            name='recent_events_card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.RecentEventsCardMst'),
        ),
    ]
