# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 00:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20170423_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenteventscarddtl',
            name='event_body_back',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='recenteventscarddtl',
            name='profile_image_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
